[profile.default]
src = "contract"
out = "out"
libs = ["lib"]
test = "test"
evm_version = "prague"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

